export const eventsData = {
    project: {
        title: "Project Presentation",
        description: "Showcase your brilliant ideas to a panel of expert dimension traversers. Holographic projector required.",
        rules: ["Max team size: 4", "10 min presentation, 5 min Q&A", "Working prototype gets bonus points"],
        time: "Day 1, 10:00 AM",
        venue: "Lab 04 - Sector B",
        theme: "tech",
        color: "#00f3ff",
    },
    cad: {
        title: "CAD Modeling",
        description: "Design the most robust Demogorgon containment unit using CAD software.",
        rules: ["Individual event", "Software provided: AutoCAD/Solidworks", "Time limit: 2 hours"],
        time: "Day 1, 01:00 PM",
        venue: "Design Nexus",
        theme: "tech",
        color: "#ff5e00",
    },
    code: {
        title: "Code Clash",
        description: "Survive the algorithm gauntlet. The code matrix is unforgiving, patch it before the breach expands.",
        rules: ["Max team size: 2", "Languages: C++, Python, Java", "No internet access allowed"],
        time: "Day 2, 09:30 AM",
        venue: "Server Room Delta",
        theme: "tech",
        color: "#00ff00",
    },
    ipl: {
        title: "IPL Auction",
        description: "Draft your dream team in this strategic simulation. Resource management is key.",
        rules: ["Max team size: 3", "Virtual budget of 100Cr", "Mock bidding process before actual"],
        time: "Day 1, 03:00 PM",
        venue: "Arena Alpha",
        theme: "non-tech",
        color: "#ff003c",
    },
    connection: {
        title: "Connection",
        description: "Find the hidden neuro-links. Solve visual puzzles to reveal the greater picture.",
        rules: ["Team size: 2", "3 rounds of increasing difficulty", "Use logic to connect unrelated images"],
        time: "Day 2, 11:00 AM",
        venue: "Lounge Area",
        theme: "non-tech",
        color: "#9d00ff",
    },
    treasure: {
        title: "Treasure Hunt",
        description: "Navigate the school grounds following encrypted clues. Beware of the shadows.",
        rules: ["Team size: 4", "Mobile phones allowed once", "Time limit: 3 hours"],
        time: "Day 2, 02:00 PM",
        venue: "Campus Wide",
        theme: "non-tech",
        color: "#ffff00",
    },
    sharktank: {
        title: "Shark Tank",
        description: "Pitch your startup concept to the investors of the Upside Down.",
        rules: ["Team size: 2-3", "5 min pitch, 5 min defense", "Business model canvas required"],
        time: "Day 1, 11:30 AM",
        venue: "Auditorium Hub",
        theme: "mixed",
        color: "#ff00ff",
    }
};
